version: '3'
services:
    db:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3308:3306'
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 1234

volumes:
    db_data:
