name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        services:
          mysql:
            image: mysql:latest
            env:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: library
              MYSQL_USER: root
              MYSQL_PASSWORD: root
            ports:
              - 3306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 14.x
                cache: 'npm'

            - name: Configure Composer
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'

            - name: Update Composer
              run: composer update

            - name: Install Composer dependencies
              run: composer install

            - name: Install dependencies
              run: npm i

            - name: Build
              run: npm build

            - name: Create .env file
                run: |
                  echo "DB_CONNECTION=mysql" >> .env
                  echo "DB_HOST=localhost" >> .env
                  echo "DB_PORT=3306" >> .env
                  echo "DB_DATABASE=library" >> .env
                  echo "DB_USERNAME=root" >> .env
                  echo "DB_PASSWORD=root" >> .env


            - name: Run tests
              run: npm test
