name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: library
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Configure Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Update Composer
        run: composer update

      - name: Install Composer dependencies
        run: composer install

      - name: Install dependencies
        run: npm i

      - name: Create .env file
        run: chmod +x setup_env.sh && ./setup_env.sh

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test
