name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 14.x
                cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Configure Composer
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'
                composer-version: '2'

            - name: Install Composer dependencies
              run: composer install

            - name: Run tests
              run: npm test
